import React from "react";
import { Link } from "react-router-dom";
import Carousel from "react-grid-carousel";
import News from "./News";
import { LeftArrow, RightArrow } from "../../commonComponents/CarouselButton";
import Education from "./Education";
import { NavHashLink } from "react-router-hash-link";
import Footer from "../../commonComponents/Footer";
import NavBar from "../../commonComponents/NavBar";
import ArticleData from "../../assets/ArticlesEduPage.json";
import Card from "./Card";

const MainData = [
  {
    ImageSrc: "https://i.postimg.cc/y60sd0pQ/article-removebg-preview.png",
    Type: "Article",
    linkToSection: "/resources/#articles",
  },
  {
    ImageSrc: "https://i.postimg.cc/4x2TMPnd/education-removebg-preview.png",
    Type: "Education",
    linkToSection: "/resources/#education",
  },
  {
    ImageSrc: "https://i.postimg.cc/0yCm0fSL/news.jpg",
    Type: "Why REI",
    linkToSection: "/resources/#REI",
  },
  {
    ImageSrc: "https://i.postimg.cc/d3p1B7Qk/keywords.jpg",
    Type: "Keywords",
    linkToSection: "/resources/#keywords",
  },
];

const KeywordData = [
  {
    title: "Capitalization Rate (Cap Rate)",
    content: `In real estate investment, the capitalization rate, often abbreviated as "cap rate", is a metric used to estimate the potential return on an investment property. It's calculated by dividing the property's net operating income (NOI) by its current market value or purchase price.`,
  },
  {
    title: "Net Operating Incone (NOI)",
    content: "Net Operating Income (NOI) is a key financial metric used to evaluate the profitability and performance of income-producing properties. It represents the total income generated by a property minus all operating expenses, excluding any mortgage payments, income taxes, or depreciation.",
  },
  {
    title: "Holding Perdiod",
    content: "The holding period refers to the length of time that an investor plans to hold onto a particular property before selling it. It is a crucial aspect of the investment strategy and can significantly impact the overall return on investment (ROI) and profitability of the investment.",
  },
  {
    title: "Due Diligence",
    content: "Due Diligence refers to the process of conducting thorough research, investigation, and analysis of a property before finalizing the purchase or investment transaction. It is a critical step that helps investors assess the property's financial, legal, and physical aspects to make informed investment decisions and mitigate risks.",
  },
  {
    title: "Accredited Investor",
    content: "Accredited investors are deemed to have sufficient financial sophistication and resources to understand and bear the risks associated with certain types of investments, including private placements and offerings of securities.",
  },
]

const reiData = [
  {
    title: "Steady Income from Rental Properties",
    description: "Real estate can generate steady income through rental properties",
    linkText: "Learn More",
    modalContent: [<h2 className="text-3xl mb-4">Steady Income from Rental Properties</h2>, `Investing in rental properties can provide investors with a steady and reliable income stream. When an investor purchases a rental property, they typically lease it out to tenants who pay rent on a regular basis, usually monthly. This rental income constitutes a consistent source of cash flow for the investor. Unlike some other forms of investment income, such as dividends from stocks, rental income tends to be more stable and predictable. This stability is often attributed to the essential nature of housing, as people will always need a place to live. Additionally, rental agreements typically involve long-term leases, providing a degree of security for the investor. Even during economic downturns, rental properties can continue to generate income, albeit potentially at slightly lower rates depending on market conditions. Overall, the steady income from rental properties can offer investors financial stability and a reliable source of passive income over the long term.`]

  },
  {
    title: "Inflation Hedge",
    description: "Real estate can serve as a hedge against inflation. As the cost of living increases, so does the value of real estate properties",
    linkText: "Learn More",
    modalContent: [<h2 className="text-3xl mb-4">Inflation Hedge</h2>, `Investing in real estate serves as an effective hedge against inflation due to its tendency to appreciate in value over time. Inflation erodes the purchasing power of money, causing prices to rise gradually. However, real estate values often rise along with inflation, allowing property owners to maintain or even increase their wealth. This is primarily because real estate assets are finite and in constant demand, especially in growing economies where population growth and urbanization drive the need for housing and commercial space. As the cost of goods and services increases, so does the value of real estate properties, making them a reliable store of wealth. Moreover, rental income from real estate investments tends to increase with inflation, as landlords can adjust rental rates to match rising living costs. Additionally, real estate investors can take advantage of fixed-rate mortgages, which become more affordable in real terms as inflation rises. Overall, real estate investments offer investors a tangible and reliable means of preserving their wealth and mitigating the effects of inflation over the long term.`]
  },
  {
    title: "Tax Benefits",
    description: "Real estate investors may benefit from various tax advantages.",
    linkText: "Learn More",
    modalContent: [<h2 className="text-3xl mb-4">Tax Benefits</h2>, `Investing in real estate offers various tax benefits that can significantly enhance investors' financial returns. One key advantage is the ability to deduct expenses associated with owning and operating rental properties, including mortgage interest, property taxes, maintenance costs, insurance premiums, and depreciation. These deductions can significantly reduce the taxable income generated by rental properties, resulting in lower overall tax liability. Additionally, real estate investors may benefit from tax-deferred exchanges, such as 1031 exchanges, which allow them to defer capital gains taxes when selling a property and reinvesting the proceeds into a similar property. Moreover, real estate investments qualify for preferential tax treatment on long-term capital gains, with lower tax rates compared to ordinary income. Investors can also leverage strategies such as cost segregation to accelerate depreciation deductions and maximize tax savings. Overall, the favorable tax treatment of real estate investments can help investors preserve more of their income and enhance their after-tax returns, making real estate an attractive asset class for tax-conscious investors.`]
  },
  {
    title: "Leverage",
    description: "Leverage can amplify returns, potentially increasing the overall profitability of the investment.",
    linkText: "Learn More",
    modalContent: [<h2 className="text-3xl mb-4">Leverage</h2>, `Leverage is a powerful tool that real estate investors utilize to amplify their returns and expand their investment portfolios. Unlike some other forms of investment, real estate allows investors to use borrowed funds, typically through mortgages, to finance a significant portion of the property's purchase price. By leveraging debt, investors can control a more substantial asset than they could afford with their own capital alone. This ability to magnify the potential return on investment is one of the key advantages of real estate investing. Additionally, because real estate values tend to appreciate over time, leveraging allows investors to multiply the growth on their equity. For example, if an investor purchases a property with a 20% down payment and the property appreciates by 5% annually, the return on investment is effectively amplified to 25% due to the leverage. However, it's important to recognize that leveraging also increases risk, as borrowing magnifies both gains and losses. Therefore, investors must carefully manage their debt levels and ensure they can cover mortgage payments even during periods of market downturns. Overall, leverage is a fundamental strategy in real estate investing that, when used wisely, can significantly enhance investors' wealth-building potential.`]
  },
  {
    title: "Demand Stability",
    description: "There is always demand for real estate, whether for residential, commercial, or industrial purposes",
    linkText: "Learn More",
    modalContent: [<h2 className="text-3xl mb-4">Demand Stability</h2>, `Demand stability is a fundamental characteristic of real estate investment that stems from the persistent and essential need for shelter and commercial space. Regardless of economic conditions, people will always require housing, whether it be for rent or purchase, ensuring a consistent level of demand in the real estate market. This stability is further bolstered by demographic factors such as population growth, urbanization, and changes in household formation rates, which continuously drive the need for residential properties. Similarly, businesses require office, retail, and industrial spaces to operate, creating ongoing demand for commercial real estate. Additionally, factors such as immigration, job growth, and lifestyle changes influence demand dynamics, contributing to the resilience of the real estate market. Unlike some other investment assets, real estate benefits from its physical presence and utility, making it less susceptible to rapid fluctuations in demand. Overall, the enduring need for real estate properties ensures a stable and predictable demand environment, providing investors with confidence in their investment decisions and long-term viability.`]
  },
  {
    title: "Potential for Value-Adding Improvements",
    description: "Real estate investors can increase the value of their properties through renovations, improvements, or development projects.",
    linkText: "Learn More",
    modalContent: [<h2 className="text-3xl mb-4">Potential for Value-Adding Improvements</h2>, `Real estate investments offer significant potential for value-added improvements, allowing investors to enhance the value and profitability of their properties. These improvements can take various forms, including renovations, upgrades, expansions, and redevelopment projects. By strategically investing in improvements, investors can increase the attractiveness, functionality, and marketability of their properties, thereby commanding higher rental income or resale values. For example, renovations such as kitchen upgrades, bathroom remodels, or modernizing outdated features can significantly enhance the appeal of residential properties, attracting higher-quality tenants willing to pay higher rents. Similarly, commercial properties can benefit from improvements such as aesthetic enhancements, technological upgrades, or reconfigurations to optimize space utilization and accommodate evolving tenant needs. Moreover, value-added improvements provide investors with the opportunity to differentiate their properties from competitors, mitigate obsolescence risks, and capitalize on emerging market trends. However, it's essential for investors to carefully analyze the costs, benefits, and potential returns associated with each improvement project to ensure they align with their investment objectives and budget constraints.`]
  },
]


function ResouceContent() {
  const description =
    "According to the survey released on Tuesday, March 5, at the 17th edition of the FICCI Real Estate Summit, there was a 7 per cent increase in investors considering residential real estate as a viable investment option, with 36 per cent of expected buyers viewing properties as an investment option in the latter half of 2023. The Indian real estate industry has experienced a significant positive shift in homebuyer sentiment and investment during the second half of 2023, as per a recent survey conducted by trade body FICCI and real estate consultant Anarock.";
  const shortDescription = description.substring(0, 150) + "... see more";

  return (
    <div className="max-w-7xl mx-auto px-4 vsm:px-6 lg:px-8 py-8 -mt-[200px] lg:-mt-[240px] xl:-mt-[300px]">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="flex flex-col pt-1 bg-white/30 backdrop-blur-xl shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)] rounded-lg">
          <div className="flex items-center justify-center bg-[url('https://i.pinimg.com/564x/11/91/c2/1191c215e4e5d4f9deb3bfbe544313c2.jpg')] vsm:w-[220px] msm:w-[300px] sm:w-[340px] vsm:h-[150px] md:w-[300px] md:h-[200px] lg:w-[400px] xl:w-[500px]  mx-auto mt-4 rounded-lg"></div>
          <div className="p-4">
            <p className="text-xs uppercase font-['Playfair-Display'] mb-2">
              Time to invest
            </p>
            <p className="font-semibold hover:underline font-['Playfair-Display'] mb-2">
              7% rise in investors in residential properties in second half of
              2023
            </p>
            <p className="text-sm">{shortDescription}</p>
          </div>
        </div>
        <div className="grid grid-cols-2 grid-rows-2 gap-4">
          {MainData.map((data, index) => (
            <NavHashLink to={data.linkToSection} smooth
              key={index}
              className="py-8 flex flex-col items-center justify-center bg-white/20 backdrop-blur-xl rounded-lg shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)]"
            >
              <div className="vsm:w-[110px]   msm:w-[120px] sm:w-[140px] vsm:h-[70px] md:w-[145px] lg:w-[200px] lg:h-[80px]  xl:w-[220px]  xl:h-[100px] flex justify-center items-center border-2 border-[#6e30a7]">
                <p className="flex items-center justify-center uppercase font-['Playfair-Display'] vsm:text-lg md:text-xl lg:text-3xl  text-[#6e30a7]  md:mt-0">
                  {data.Type}
                </p>
              </div>
            </NavHashLink>
          ))}
        </div>
      </div>
      <div className="pt-6" id="education">
        <h1 className="text-4xl my-[20px] text-white pb-6 flex justify-center font-['Playfair-Display']">
          EDUCATION
        </h1>
        <Education />
      </div>
      <div className="pt-6" id="articles">
        <h1 className="text-4xl my-[20px] text-white pb-6 flex justify-center font-['Playfair-Display']">
          ARTICLES
        </h1>
        <div className="">
          <Carousel
            cols={2}
            rows={1}
            gap={10}
            arrowLeft={<LeftArrow dir="left" />}
            arrowRight={<RightArrow dir="left" />}
            loop
          >
            {ArticleData.map((article, index) => (
              <Carousel.Item key={index}>
                <div className="bg-white/20 backdrop-blur-xl font-['Playfair-Display'] shadow-md rounded-md w-full p-6 mb-4 vsm:h-full md:h-[300px] lg:h-[250px]">
                  <h2 className="text-lg font-semibold text-gray-800 text-left ">
                    {article.title}
                  </h2>
                  <div className="mt-2">
                    <p className="text-black md:hidden">
                      {article.desc.length > 175
                        ? `${article.desc.substring(0, 165)}...`
                        : article.desc}
                    </p>
                    <p className="text-black vsm:hidden md:block">
                      {article.desc.length > 210
                        ? `${article.desc.substring(0, 200)}...`
                        : article.desc}
                    </p>
                  </div>
                  <div className="mt-4">
                    <Link
                      to={article.url}
                      target="_blank"
                      className="text-[#6e30a7] hover:underline "
                    >
                      Read More
                    </Link>
                  </div>
                </div>
              </Carousel.Item>
            ))}
          </Carousel>
        </div>
      </div>
      <div className="pt-6" id="keywords">
        <h1 className="text-4xl my-[20px] text-white pb-6 flex justify-center font-['Playfair-Display']">
          KEYWORDS
        </h1>
        <div className="">
          <Carousel
            cols={2}
            rows={1}
            gap={10}
            arrowLeft={<LeftArrow dir="right" />}
            arrowRight={<RightArrow dir="right" />}
            loop
          >
            {KeywordData.map((keywords, index) => (
              <Carousel.Item key={index}>
                <div className="bg-white/20 backdrop-blur-xl font-['Playfair-Display'] shadow-md rounded-md w-full p-6 mb-4 vsm:h-[400px] md:h-[300px] lg:h-[200px]">
                  <h2 className="text-lg font-semibold text-gray-800 text-center ">
                    {keywords.title}
                  </h2>
                  <div className="mt-2">
                    <p className="text-black">
                      {keywords.content}
                    </p>
                  </div>
                </div>
              </Carousel.Item>
            ))}
          </Carousel>
        </div>
      </div>
      <div className="py-8" id="REI">
        <h1 className="text-4xl my-[20px] text-white  pb-6 flex justify-center font-['Playfair-Display']">
          Why Real Estate Investments
        </h1>
        <div className="bg-white/20 backdrop-blur-xl p-4 rounded-lg pb-6 shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)]">
          <h1 className="text-xl font-semibold font-['Playfair-Display'] text-center mb-4 text-black uppercase">
            Why choose real estate investments
          </h1>
          <div className="flex font-['Playfair-Display'] flex-wrap">
            {reiData.map((data, index) => (
              <div className="w-full md:w-1/2 lg:w-1/3 p-2" key={index}>
                <Card data={data} />
              </div>
            ))}
          </div>
        </div>
      </div>

    </div>
  )
};

function EducationPage() {
  return (
    <div className="">
      <div className="categoryMain">
        <NavBar />
        <div className="h-[85vh] overflow-hidden flex items-center vsm:justify-center lg:justify-end">
          <p className="uppercase font-['Playfair-Display'] lg:text-5xl xl:text-6xl text-white vsm:text-4xl md:text-5xl lg:-mt-[350px] lg:mr-[220px] xl:-mt-[430px] xl:mr-[250px] ">
            RESOURCES
          </p>
        </div>
      </div>
      < ResouceContent />
      <div className="">
        <Footer />
      </div>
    </div>
  );
}

export default EducationPage;
